ALTER SESSION SET CONTAINER=PDB;
CREATE USER employee_manager IDENTIFIED BY "employee_manager";
GRANT CREATE SESSION TO employee_manager;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE SYNONYM TO employee_manager;
GRANT CREATE PROCEDURE TO employee_manager;
GRANT CREATE TRIGGER TO employee_manager;
GRANT UNLIMITED TABLESPACE TO employee_manager;